#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-rocksdb
Version  : 5.18.3
Release  : 1
URL      : https://github.com/facebook/rocksdb/archive/v5.18.3.tar.gz
Source0  : https://github.com/facebook/rocksdb/archive/v5.18.3.tar.gz
Source1  : https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/5.18.3/rocksdbjni-5.18.3.jar
Source2  : https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/5.18.3/rocksdbjni-5.18.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause CC-BY-4.0 GPL-2.0
Requires: mvn-rocksdb-data = %{version}-%{release}
Requires: mvn-rocksdb-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
This folder defines a REDIS-style interface for Rocksdb.
Right now it is written as a simple tag-on in the rocksdb::RedisLists class.
It implements Redis Lists, and supports only the "non-blocking operations".

%package data
Summary: data components for the mvn-rocksdb package.
Group: Data

%description data
data components for the mvn-rocksdb package.


%package license
Summary: license components for the mvn-rocksdb package.
Group: Default

%description license
license components for the mvn-rocksdb package.


%prep
%setup -q -n rocksdb-5.18.3

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-rocksdb
cp COPYING %{buildroot}/usr/share/package-licenses/mvn-rocksdb/COPYING
cp LICENSE.Apache %{buildroot}/usr/share/package-licenses/mvn-rocksdb/LICENSE.Apache
cp LICENSE.leveldb %{buildroot}/usr/share/package-licenses/mvn-rocksdb/LICENSE.leveldb
cp docs/LICENSE-DOCUMENTATION %{buildroot}/usr/share/package-licenses/mvn-rocksdb/docs_LICENSE-DOCUMENTATION
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/rocksdb/rocksdbjni/5.18.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/rocksdb/rocksdbjni/5.18.3/rocksdbjni-5.18.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/rocksdb/rocksdbjni/5.18.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/rocksdb/rocksdbjni/5.18.3/rocksdbjni-5.18.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/rocksdb/rocksdbjni/5.18.3/rocksdbjni-5.18.3.jar
/usr/share/java/.m2/repository/org/rocksdb/rocksdbjni/5.18.3/rocksdbjni-5.18.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-rocksdb/COPYING
/usr/share/package-licenses/mvn-rocksdb/LICENSE.Apache
/usr/share/package-licenses/mvn-rocksdb/LICENSE.leveldb
/usr/share/package-licenses/mvn-rocksdb/docs_LICENSE-DOCUMENTATION
